spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config # \uC11C\uBE44\uC2A4 \uD504\uB85C\uC81D\uD2B8\uC758 application.yaml \uD30C\uC77C\uC744 config/ \uD3F4\uB354\uC548\uC5D0 \uC788\uB294 \uC124\uC815\uD30C\uC77C\uC744 \uCC38\uC870\uD558\uACA0\uB2E4\uB294 \uC758\uBBF8
        encrypt:
          enabled: false

server:
  port: 8080