logging:
  file:
    name: logs/authentication.log
  logback:
    rollingpolicy:
      max-history: 10
      max-file-size: 500MB
  level:
    root: info
    org.msa.authentication: debug #org.msa.item 패키지는 debug 레벨로 출력
    org.hibernate:
      orm:
        jdbc:
          bind: trace

spring:
  config:
    import:
      - classpath:/config/datasource-local.yaml


eureka:
  instance:
    prefer-ip-address: true # hostname이 아닌 IP 주소로 Eureka server에 등록하겠냐는 옵션
  client:
    register-with-eureka: true # Eureka에 등록을 하겠냐는 옵션
    fetch-registry: true # registry에 저장된 내용을 캐시해서 출력하겠냐는 옵션
    service-url: # Eureka URl
      defaultZone: http://localhost:8761/eureka

