spring:
  datasource:
    url: jdbc:mysql://localhost:3306/item_example?serverTimezone=Asia/Seoul
    username: root
    password: '{cipher}9716b0d3de518ae1e59e7544dff60c1fcc0fe34ff0eaa32988105575f796b69e'
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 40
  sql.init.mode: never
  jpa:
    hibernate:
      ddl-auto: create  # create, update, validate, none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul
    open-in-view: false
