logging:
  file:
    name: logs/api.log
    test: 22
  logback:
    rollingpolicy:
      max-history: 10
      max-file-size: 500MB
  level:
    root: info
    org.msa.item: debug #org.msa.item 패키지는 debug 레벨로 출력
    org.hibernate:
      orm:
        jdbc:
          bind: trace

spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  instance: # 연동할 eureka의 서비스명
    hostname: eureka-server
  client:
    serviceUrl: # Eureka 서버의 url 정보를 설정
      defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false # eureka 서버에 서버 관련 정보를 등록할것이냐 인데 굳이 eureka 서버안에 eureka 정보를 저장할 필요가 없기때문에 false
    fetch-registry: false # 다른 서비스 레지스트리 정보를 가져오지 않음
management:
  endpoints:
    web:
      exposure:
        include: "*"