spring:
  datasource:
    url: jdbc:mysql://localhost:33306/item_example?serverTimezone=Asia/Seoul
    username: root
    password: '{cipher}9716b0d3de518ae1e59e7544dff60c1fcc0fe34ff0eaa32988105575f796b69e'
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 40

  sql.init.mode: never
  jpa:
    hibernate:
      ddl-auto: create  # create, update, validate, none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul
    open-in-view: false

logging:
  file:
    name: logs/api-local.log
    test: 22
  logback:
    rollingpolicy:
      max-history: 10
      max-file-size: 10MB
  level:
    root: info
    org.msa.item: debug #org.msa.item 패키지는 debug 레벨로 출력
    org.hibernate:
      orm:
        jdbc:
          bind: trace
#http://localhost:8080/swagger-ui/index.html
springdoc:
  # enabled: false  # Swagger UI 사용 금지(운영일경우)
  # api 함수에 대해서 media-type을 지정하지 않았을때
  # 웹 문서에서 기본적으로 API 기능 설명에 대해서 application/json 형식으로 주고받는 기능이다 라고 출력될 예정이다라고 설정한것
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    # 함수명에 대해서 알파벳 기준으로 오름차순으로 문서를 정렬하겠다는 의미.
    operations-sorter: alpha
    # 태그명에 대해서 알파벳 기준으로 오름차순으로 정렬하겠다는 의미
    tags-sorter: alpha
    # path 설정은 springdoc 문서 HTML를 출력할 URI 설정
    path: /swagger-ui.html
    # petstore html(OpenAPI(Swagger) 샘플 문서, API 명세서 예제) 문서를 비활성화 하는 옵션으로 불필요한 petstore 관련 API 문서 내용이 추가됨
    disable-swagger-default-url: true
    # url 쿼리매개변수를 이용해서 swagger-ui에 대한 처리를 활성화
    display-query-params-without-oauth2: false

token:
  expiration_time: 86400000
  secret: SECU100