spring:
  datasource:
    url: jdbc:mysql://localhost:33306/item_example?serverTimezone=Asia/Seoul
    username: root
    password: root01
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 40

  sql.init.mode: never
  jpa:
    hibernate:
      ddl-auto: create  # create, update, validate, none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul
    open-in-view: false

logging:
  file:
    name: logs/api.log
  logback:
    rollingpolicy:
      max-history: 10
      max-file-size: 10MB
  level:
    root: info
    org.msa.item: debug #org.msa.item ??? debug ??? ???? ???